# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.models
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_title', models.CharField(blank=True, max_length=200, null=True)),
                ('header_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('about_title', models.CharField(blank=True, max_length=300, null=True)),
                ('about_text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('mr_title', models.CharField(blank=True, max_length=300, null=True)),
                ('mr_text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('wx_title', models.CharField(blank=True, max_length=300, null=True)),
                ('studies_title', models.CharField(blank=True, max_length=300, null=True)),
                ('services_title', models.CharField(blank=True, max_length=250)),
                ('skill_title', models.CharField(blank=True, max_length=250)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('header_bg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('header_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=250)),
                ('logo', models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase'), ('icon-paintbrush', 'Paint brush'), ('icon-briefcase', 'briefcase'), ('icon-search', 'search'), ('icon-bargraph', 'bargraph'), ('icon-chat', 'chat')], max_length=250)),
                ('text', models.TextField(blank=True)),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=250)),
                ('value', home.models.IntegerRangeField()),
                ('color', models.CharField(max_length=250)),
                ('graph_type', models.CharField(choices=[('bar', 'bar'), ('circle', 'circle')], default='bar', max_length=250)),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('logo_class', models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase'), ('icon-paintbrush', 'Paint brush'), ('icon-briefcase', 'briefcase'), ('icon-search', 'search'), ('icon-bargraph', 'bargraph'), ('icon-chat', 'chat')], max_length=250)),
                ('url', models.URLField(blank=True, null=True)),
                ('logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeLineStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('orientation', models.CharField(choices=[('timeline-unverted', 'right'), ('timeline-inverted', 'left')], max_length=100)),
                ('text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('logo', models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase'), ('icon-paintbrush', 'Paint brush'), ('icon-briefcase', 'briefcase'), ('icon-search', 'search'), ('icon-bargraph', 'bargraph'), ('icon-chat', 'chat')], max_length=250)),
                ('related_time_studies', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_line_study', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeLineWorkXP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('orientation', models.CharField(choices=[('timeline-unverted', 'right'), ('timeline-inverted', 'left')], max_length=100)),
                ('text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('logo', models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase'), ('icon-paintbrush', 'Paint brush'), ('icon-briefcase', 'briefcase'), ('icon-search', 'search'), ('icon-bargraph', 'bargraph'), ('icon-chat', 'chat')], max_length=250)),
                ('related_time_work', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_line_work', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
