# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_header_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
