# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0004_auto_20171012_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
