# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='logo_class',
            field=models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter')], max_length=250),
        ),
    ]
