# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171013_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mr_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mr_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
