# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20171013_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('orientation', models.CharField(choices=[('timeline-unverted', 'right'), ('timeline-inverted', 'left')], max_length=100)),
                ('text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('logo', models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase')], max_length=250)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeLineWorkXP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('orientation', models.CharField(choices=[('timeline-unverted', 'right'), ('timeline-inverted', 'left')], max_length=100)),
                ('text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('logo', models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase')], max_length=250)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='page',
        ),
        migrations.RemoveField(
            model_name='timelineitem',
            name='related_time_line',
        ),
        migrations.AddField(
            model_name='homepage',
            name='studies_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='wx_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='TimeLine',
        ),
        migrations.DeleteModel(
            name='TimeLineItem',
        ),
        migrations.AddField(
            model_name='timelineworkxp',
            name='related_time_work',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_line_work', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='timelinestudies',
            name='related_time_studies',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_line_study', to='home.HomePage'),
        ),
    ]
