# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20171014_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=250)),
                ('logo', models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase'), ('icon-paintbrush', 'Paint brush'), ('icon-briefcase', 'briefcase'), ('icon-search', 'search'), ('icon-bargraph', 'bargraph'), ('icon-chat', 'chat')], max_length=250)),
                ('text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='logo_class',
            field=models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase'), ('icon-paintbrush', 'Paint brush'), ('icon-briefcase', 'briefcase'), ('icon-search', 'search'), ('icon-bargraph', 'bargraph'), ('icon-chat', 'chat')], max_length=250),
        ),
        migrations.AlterField(
            model_name='timelinestudies',
            name='logo',
            field=models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase'), ('icon-paintbrush', 'Paint brush'), ('icon-briefcase', 'briefcase'), ('icon-search', 'search'), ('icon-bargraph', 'bargraph'), ('icon-chat', 'chat')], max_length=250),
        ),
        migrations.AlterField(
            model_name='timelineworkxp',
            name='logo',
            field=models.CharField(blank=True, choices=[('icon-linkedin2', 'linkedn'), ('icon-facebook2', 'Facebook'), ('icon-twitter2', 'Twitter'), ('icon-graduation-cap', 'Graduation'), ('icon-suitcase', 'Suitecase'), ('icon-paintbrush', 'Paint brush'), ('icon-briefcase', 'briefcase'), ('icon-search', 'search'), ('icon-bargraph', 'bargraph'), ('icon-chat', 'chat')], max_length=250),
        ),
        migrations.AddField(
            model_name='services',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.HomePage'),
        ),
    ]
