# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20171015_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=250)),
                ('value', home.models.IntegerRangeField()),
                ('color', models.CharField(max_length=250)),
                ('graph_type', models.CharField(choices=[('bar', 'bar'), ('circle', 'circle')], default='bar', max_length=250)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.HomePage'),
        ),
    ]
