# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20171015_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
